"""separando modelos deusuario

Revision ID: f60cd8f506df
Revises: a7dccba1db28
Create Date: 2025-06-10 23:24:39.184402-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60cd8f506df'
down_revision = 'a7dccba1db28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###