"""removiendo relaciones problematicas

Revision ID: a7dccba1db28
Revises: 7fe5c6bbe845
Create Date: 2025-06-10 23:18:29.273553-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7dccba1db28'
down_revision = '7fe5c6bbe845'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###