"""authentication models

Revision ID: debb6f428bd3
Revises: 3f9ce60d42ff
Create Date: 2025-06-11 20:10:51.868629-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debb6f428bd3'
down_revision = '3f9ce60d42ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###