"""Fix user model relationships and foreign keys

Revision ID: 7fe5c6bbe845
Revises: 23c880c13c7d
Create Date: 2025-06-10 23:14:45.078638-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe5c6bbe845'
down_revision = '23c880c13c7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_role_primary'))
        batch_op.drop_index(batch_op.f('idx_user_role_role_active'))
        batch_op.drop_index(batch_op.f('idx_user_role_type_filter'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_role_type_filter'), ['user_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_role_role_active'), ['role_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_role_primary'), ['user_id', 'user_type', 'is_primary'], unique=False)

    # ### end Alembic commands ###