"""initial migrationv2

Revision ID: 3f9ce60d42ff
Revises: 5f00265c85e8
Create Date: 2025-06-11 09:37:20.914938-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9ce60d42ff'
down_revision = '5f00265c85e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###