"""Add performance indexes

Revision ID: 23c880c13c7d
Revises: 949d0aba1e9d
Create Date: 2025-06-10 22:42:47.049023-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c880c13c7d'
down_revision = '949d0aba1e9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutional_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_locked', sa.Boolean(), nullable=False))
        batch_op.create_index('idx_institutional_user_active_created', ['is_active', 'created_at'], unique=False)
        batch_op.create_index('idx_institutional_user_institution', ['institution'], unique=False)
        batch_op.create_index('idx_institutional_user_search', ['first_name', 'last_name', 'username'], unique=False)
        batch_op.create_index('idx_institutional_user_types', ['is_faculty', 'is_student', 'is_external_client'], unique=False)
        batch_op.create_index('idx_institutional_user_uuid', ['uuid'], unique=False)

    with op.batch_alter_table('internal_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_locked', sa.Boolean(), nullable=False))
        batch_op.create_index('idx_internal_user_active_created', ['is_active', 'created_at'], unique=False)
        batch_op.create_index('idx_internal_user_dashboard_access', ['can_access_dashboard'], unique=False)
        batch_op.create_index('idx_internal_user_search', ['first_name', 'last_name', 'username'], unique=False)
        batch_op.create_index('idx_internal_user_uuid', ['uuid'], unique=False)

    with op.batch_alter_table('user_academic_units', schema=None) as batch_op:
        batch_op.create_index('idx_user_academic_unit_budget', ['user_id', 'has_budget_authority'], unique=False)
        batch_op.create_index('idx_user_academic_unit_primary', ['user_id', 'is_primary'], unique=False)
        batch_op.create_index('idx_user_academic_unit_relationship', ['relationship_type'], unique=False)
        batch_op.create_index('idx_user_academic_unit_represent', ['user_id', 'can_represent_unit'], unique=False)
        batch_op.create_index('idx_user_academic_unit_unit_active', ['academic_unit_id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_academic_unit_user_active', ['user_id', 'is_active'], unique=False)

    with op.batch_alter_table('user_areas', schema=None) as batch_op:
        batch_op.create_index('idx_user_area_area_active', ['area_id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_area_can_lead', ['user_id', 'can_lead_projects'], unique=False)
        batch_op.create_index('idx_user_area_primary', ['user_id', 'is_primary'], unique=False)
        batch_op.create_index('idx_user_area_user_active', ['user_id', 'is_active'], unique=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('idx_user_role_primary', ['user_id', 'user_type', 'is_primary'], unique=False)
        batch_op.create_index('idx_user_role_role_active', ['role_id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_role_type_filter', ['user_type'], unique=False)
        batch_op.create_index('idx_user_role_user_type', ['user_id', 'user_type'], unique=False)
        batch_op.create_index('idx_user_role_user_type_active', ['user_id', 'user_type', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('idx_user_role_user_type_active')
        batch_op.drop_index('idx_user_role_user_type')
        batch_op.drop_index('idx_user_role_type_filter')
        batch_op.drop_index('idx_user_role_role_active')
        batch_op.drop_index('idx_user_role_primary')

    with op.batch_alter_table('user_areas', schema=None) as batch_op:
        batch_op.drop_index('idx_user_area_user_active')
        batch_op.drop_index('idx_user_area_primary')
        batch_op.drop_index('idx_user_area_can_lead')
        batch_op.drop_index('idx_user_area_area_active')

    with op.batch_alter_table('user_academic_units', schema=None) as batch_op:
        batch_op.drop_index('idx_user_academic_unit_user_active')
        batch_op.drop_index('idx_user_academic_unit_unit_active')
        batch_op.drop_index('idx_user_academic_unit_represent')
        batch_op.drop_index('idx_user_academic_unit_relationship')
        batch_op.drop_index('idx_user_academic_unit_primary')
        batch_op.drop_index('idx_user_academic_unit_budget')

    with op.batch_alter_table('internal_users', schema=None) as batch_op:
        batch_op.drop_index('idx_internal_user_uuid')
        batch_op.drop_index('idx_internal_user_search')
        batch_op.drop_index('idx_internal_user_dashboard_access')
        batch_op.drop_index('idx_internal_user_active_created')
        batch_op.drop_column('account_locked')

    with op.batch_alter_table('institutional_users', schema=None) as batch_op:
        batch_op.drop_index('idx_institutional_user_uuid')
        batch_op.drop_index('idx_institutional_user_types')
        batch_op.drop_index('idx_institutional_user_search')
        batch_op.drop_index('idx_institutional_user_institution')
        batch_op.drop_index('idx_institutional_user_active_created')
        batch_op.drop_column('account_locked')

    # ### end Alembic commands ###