"""Add CMS models: Category, Video, Gallery

Revision ID: 449ec97c3fce
Revises: 4117da078229
Create Date: 2025-06-10 19:27:30.013351-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449ec97c3fce'
down_revision = '4117da078229'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###