"""Correccion UUID cms

Revision ID: 3047e5b0c914
Revises: debb6f428bd3
Create Date: 2025-06-12 19:08:31.888403-06:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3047e5b0c914'
down_revision = 'debb6f428bd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.CHAR(length=36), nullable=False, comment='Public unique identifier'))
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.Integer(),
               comment='Internal unique identifier',
               existing_comment='Public unique identifier',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.Integer(),
               comment='User ID who created this record',
               existing_comment='User UUID who created this record',
               existing_nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.Integer(),
               comment='User ID who last updated this record',
               existing_comment='User UUID who last updated this record',
               existing_nullable=True)
        batch_op.create_index('idx_gallery_uuid', ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_galleries_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.CHAR(length=36), nullable=False, comment='Public unique identifier'))
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.Integer(),
               comment='Internal unique identifier',
               existing_comment='Public unique identifier',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.Integer(),
               comment='User ID who created this record',
               existing_comment='User UUID who created this record',
               existing_nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.Integer(),
               comment='User ID who last updated this record',
               existing_comment='User UUID who last updated this record',
               existing_nullable=True)
        batch_op.create_index('idx_video_uuid', ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_uuid'))
        batch_op.drop_index('idx_video_uuid')
        batch_op.alter_column('updated_by',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=36),
               comment='User UUID who last updated this record',
               existing_comment='User ID who last updated this record',
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=36),
               comment='User UUID who created this record',
               existing_comment='User ID who created this record',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=36),
               comment='Public unique identifier',
               existing_comment='Internal unique identifier',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('uuid')

    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galleries_uuid'))
        batch_op.drop_index('idx_gallery_uuid')
        batch_op.alter_column('updated_by',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=36),
               comment='User UUID who last updated this record',
               existing_comment='User ID who last updated this record',
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=36),
               comment='User UUID who created this record',
               existing_comment='User ID who created this record',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=36),
               comment='Public unique identifier',
               existing_comment='Internal unique identifier',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###